imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

pourquoi_be2bill_simulation:
    template_url: ""
    template_mobile_url: ""
    notification_url: ""
    identifier: "id_test"
    password: "pass_test"
    return_url: ""