payment_be2bill_simulation_form_process:
    pattern: /front/form/process
    defaults: { _controller: PourquoiBe2billSimulationBundle:Simulation:formProcess }
    requirements:
        _method: POST

payment_be2bill_simulation_form_process_payment:
    pattern: /front/form/process_payment
    defaults: { _controller: PourquoiBe2billSimulationBundle:Simulation:formProcessPayment }
    requirements:
        _method: POST

payment_be2bill_simulation_payment_feedback:
    pattern: /front/payment_feedback
    defaults: { _controller: PourquoiBe2billSimulationBundle:Simulation:paymentFeedback }
    requirements:
        _method: POST

payment_be2bill_simulation_rest_process:
    pattern: /front/service/rest/process
    defaults: { _controller: PourquoiBe2billSimulationBundle:Simulation:restProcess }
    requirements:
        _method: POST